DATA_DIR = '../csse_covid_19_data'
PLOTS_DIR = '../docs/plots'
INTERACTIVE_PLOTS_DIR = '../docs/interactive-plots'
PATH_TO_PLOTLY = '../assets/js/plotly.min.js'
AGGREGATE = '../docs/_data/aggregate.json'
INCLUDES_DIR = '../docs/_includes'
