theme: jekyll-theme-cayman
title: COVID19 Animated Visualizations
description: Interactive Animated Visualizations of COVID-19 Data
summary: Global COVI119 Animated Visualizations updated on Daily Basis 
google_analytics: UA-172632001-1
tage: [covid19,covid,covid19data,covidvisualization,visualization,animated,interactive]
,
